# Site settings
title: Joe's Veloschmiede
email: joe@veloschmiede.de
url: https://github.com/???
description: "Hi there! I am João de Jesus Marques and if you think we should collaborate on any project - contact me on any channel and lets have a chat!"
keywords: "Fahhräder, e-bike, Werkstatt, fahrradwerkstatt"
skills: "Fahrräder jeder Art | E-Bikes| Ergonomische anpassung "
meta_author: João de Jesus Marques

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: #000000 #FFA500
  primary-rgb: "0,0,0" "255,165,0"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: João de Jesus Marques
  location: Location
  social: Around the Web
  credits: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: xing
    url: https://www.xing.com/profile/???
  - title: linkedin
    url: https://www.linkedin.com/in/???/
  - title: facebook
    url: https://www.facebook.com/???/
  - title: github
    url: https://github.com/???

# Postal address (add as many lines as necessary)
address:
  - line: Veloschmiede
  - line: 49635 Badbergen
  - line: Am ende des Radwegs

# Credits content
credits:
  - line: <a href="tel:+49-174-6909320">+49-174-6909320</a>
  - line: <a href="mailto:joe@veloschmiede.de">joe@veloschmiede.de</a>

# <table style="width:100%; font-family: "Lato","Helvetica Neue",Helvetica,Arial,sans-serif; font-size: 15px;">
# <tr>
#   <td width="50%" align="right">phone</td>
#   <td width="50%" align="left"> <a href="tel:+49-175-2092782">+49-175-2092782</a><br></td>
# </tr>
# <tr>
#   <td width="50%" align="right">phone</td>
#   <td width="50%" align="left"> <a href="tel:+357-96-397761">+357-96-397761</a><br></td>
# </tr>
# <tr>
#   <td width="50%" align="right">mail</td>
#   <td width="50%" align="left"> <a href="mailto:sergei@waigant.com">sergei@waigant.com</a></td>
# </tr>
# </table>

# Build settings
markdown: kramdown
permalink: pretty

#for posts
# defaults:
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       permalink: ""
